name: Python application

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9' ]
    name: Python ${{ matrix.python-version }} pytest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: pip install -r requirements.txt
    - name: pytest
      run: pytest -v --junit-xml=test-reports/results.xml tests
